name: NPM Publish

on:
  release:
    types: [created]

jobs:
  publish-core:
    name: Publish Core Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          scope: '@friendsofshopware'
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Transform to NPM Package
        run: |
          cd packages/app-server-sdk
          deno run -A scripts/build.ts ${{ github.ref_name }}
      - name: Publish to NPM
        run: |
          cd packages/app-server-sdk/npm
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
