name: JSR Publish

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    permissions:
     contents: read
     id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Update version in JSR
        working-directory: src
        run: |
          jq '.version = "${{ github.event.release.tag_name }}"' jsr.json > jsr.json.tmp
          mv jsr.json.tmp jsr.json

      - name: Publish package
        working-directory: src
        run: npx jsr publish --allow-dirty
