name: NPM Publish

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - 'app-server-sdk'
          - 'app-server-sdk-cloudflare'
          - 'app-server-sdk-express'
          - 'app-server-sdk-hono'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Transform to NPM Package
        run: |
          cd packages/${{ matrix.package }}
          deno run -A scripts/build.ts ${{ github.event.release.tag_name }}
      - name: Publish to NPM
        run: |
          cd packages/${{ matrix.package }}/npm
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
 
