name: JSR Publish

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    permissions:
     contents: read
     id-token: write
    strategy:
      fail-fast: false
      matrix:
        package:
          - 'app-server-sdk'
          - 'app-server-sdk-express'

    steps:
      - uses: actions/checkout@v4

      - name: Update version in JSR
        working-directory: packages/${{ matrix.package }}
        run: |
          jq '.version = "${{ github.event.release.tag_name }}"' jsr.json > jsr.json.tmp
          mv jsr.json.tmp jsr.json

      - name: Publish package
        working-directory: packages/${{ matrix.package }}
        run: npx jsr publish
